'use client'

import { useState } from 'react'
import Image from 'next/image'
import { ArrowUpRight, Check, ChevronDown, Menu, MessageCircle, MoveRight, Sparkles, X } from 'lucide-react'

const WHATSAPP_MESSAGE = 'Olá! Conheci a Vellora e gostaria de saber mais sobre a criação de um site ou cardápio digital para o meu negócio.'
const WHATSAPP_URL = `https://wa.me/SEU_NUMERO?text=${encodeURIComponent(WHATSAPP_MESSAGE)}`
const PORTFOLIO_URL = 'SEU_LINK_DO_PORTFOLIO'

const openWhatsApp = (label: string) => {
  if (typeof window !== 'undefined') {
    window.dispatchEvent(new CustomEvent('vellora_conversion', { detail: { event: 'whatsapp_click', label } }))
    window.open(WHATSAPP_URL, '_blank', 'noopener,noreferrer')
  }
}

const services = [
  ['Landing Pages', 'Experiências estratégicas para apresentar seu negócio, gerar confiança e transformar visitantes em contatos.'],
  ['Cardápios Digitais', 'Transforme seu PDF em uma experiência moderna, responsiva e muito mais agradável para seus clientes.'],
  ['Sites para Restaurantes', 'Apresente seu cardápio, localização, horários, contato e informações importantes em um único lugar.'],
  ['Sites para Negócios Locais', 'Uma presença digital profissional para empresas que querem transmitir mais credibilidade.'],
  ['Landing Pages para Campanhas', 'Páginas desenvolvidas para campanhas de tráfego pago e geração de leads.'],
]
const benefits = [
  ['Mais profissionalismo', 'Seu negócio passa uma imagem mais moderna e confiável.'],
  ['Experiência melhor', 'Seus clientes encontram o que procuram com muito mais facilidade.'],
  ['100% responsivo', 'A experiência funciona perfeitamente em celulares, tablets e computadores.'],
  ['Mais praticidade', 'Chega de enviar arquivos PDF enormes pelo WhatsApp.'],
  ['Valorize seus produtos', 'Apresente seus produtos e serviços de uma forma muito mais atraente.'],
  ['Mais facilidade para atualizar', 'Tenha uma presença digital muito mais simples de manter.'],
]
const faqs = [
  ['Quanto custa criar uma página?', 'Cada projeto é único e o investimento depende da solução e do nível de personalização. Conte para a gente o que você precisa e enviaremos uma proposta.'],
  ['Quanto tempo leva para ficar pronta?', 'O prazo varia conforme o projeto, mas definimos tudo com clareza antes de começar.'],
  ['Vocês criam o design?', 'Sim. Cuidamos da direção visual e criamos uma experiência alinhada à sua marca.'],
  ['Posso usar meu próprio domínio?', 'Sim. Podemos conectar seu domínio atual ou orientar você na escolha de um novo.'],
  ['Vocês transformam meu PDF em um cardápio digital?', 'Sim. Organizamos o conteúdo em uma experiência responsiva, clara e fácil de navegar.'],
  ['Funciona no celular?', 'Sim. Todos os projetos são pensados primeiro para a experiência mobile.'],
  ['Depois posso atualizar o conteúdo?', 'Sim. A solução pode ser estruturada para facilitar futuras atualizações.'],
  ['Vocês atendem negócios de qualquer cidade?', 'Sim. O atendimento e o desenvolvimento podem acontecer de forma totalmente online.'],
]

function Logo({ compact = false }: { compact?: boolean }) {
  return <div className="flex items-center gap-3"><Image src="/vellora-logo.png" alt="Vellora" width={compact ? 30 : 42} height={compact ? 30 : 42} className={compact ? 'size-7 object-cover object-top' : 'h-10 w-10 object-cover object-top'} /><span className="font-mono text-sm font-bold tracking-[0.35em]">VELLORA</span></div>
}
function Button({ children, onClick, outline = false, href }: { children: React.ReactNode; onClick?: () => void; outline?: boolean; href?: string }) {
  const cls = `inline-flex min-h-12 items-center justify-center gap-3 rounded-full px-6 text-sm font-semibold transition-all ${outline ? 'border border-border bg-transparent text-foreground hover:bg-accent' : 'bg-foreground text-background hover:-translate-y-0.5 hover:shadow-[0_10px_30px_-12px_var(--foreground)]'}`
  return href ? <a className={cls} href={href} onClick={onClick}>{children}<ArrowUpRight className="size-4" /></a> : <button className={cls} onClick={onClick}>{children}<ArrowUpRight className="size-4" /></button>
}
function PhoneMockup({ modern = false }: { modern?: boolean }) {
  return <div className={`phone-mockup ${modern ? 'phone-modern' : ''}`}><div className="phone-notch" /><div className="phone-screen">{modern ? <><div className="flex items-center justify-between"><span className="font-serif text-[10px] font-bold">Seu negócio</span><span className="text-[8px] text-muted-foreground">☰</span></div><div className="mt-5 h-16 rounded-lg bg-muted" /><div className="mt-3 text-[8px] font-bold">Menu da casa</div><div className="mt-2 flex gap-1"><span className="rounded-full bg-foreground px-2 py-1 text-[6px] text-background">Entradas</span><span className="rounded-full bg-muted px-2 py-1 text-[6px]">Pratos</span></div><div className="mt-3 flex items-center justify-between border-b border-border pb-2 text-[7px]"><span>Bruschetta artesanal</span><b>R$ 32</b></div><div className="mt-3 flex items-center justify-between border-b border-border pb-2 text-[7px]"><span>Massa da casa</span><b>R$ 48</b></div><div className="mt-6 rounded-full bg-foreground py-2 text-center text-[7px] text-background">Pedir pelo WhatsApp</div></> : <><div className="mb-3 h-3 w-2/3 bg-muted" /><div className="flex flex-col gap-2">{[1,2,3,4,5,6].map(i => <div key={i} className="h-2 w-full bg-muted" />)}</div><div className="mt-8 flex flex-col gap-2"><div className="h-16 bg-muted" /><div className="h-2 w-4/5 bg-muted" /><div className="h-2 w-1/2 bg-muted" /></div></>}</div></div>
}
function SectionTitle({ eyebrow, title, text, light = false }: { eyebrow?: string; title: string; text?: string; light?: boolean }) { return <div className={`max-w-3xl ${light ? 'text-background' : ''}`}><span className="eyebrow">{eyebrow || 'VELLORA'}</span><h2 className="mt-5 text-balance font-serif text-4xl leading-[1.04] tracking-tight sm:text-5xl lg:text-6xl">{title}</h2>{text && <p className={`mt-6 max-w-xl text-base leading-7 ${light ? 'text-background/60' : 'text-muted-foreground'}`}>{text}</p>}</div> }

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [faqOpen, setFaqOpen] = useState<number | null>(null)
  const [submitted, setSubmitted] = useState(false)
  return <main className="overflow-hidden bg-background">
    <nav className="fixed inset-x-0 top-0 z-40 border-b border-border/50 bg-background/85 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8"><a href="#inicio"><Logo compact /></a><div className="hidden items-center gap-8 text-xs text-muted-foreground md:flex"><a href="#solucoes" className="hover:text-foreground">Soluções</a><a href="#portfolio" className="hover:text-foreground">Portfólio</a><a href="#processo" className="hover:text-foreground">Como funciona</a><a href="#faq" className="hover:text-foreground">FAQ</a></div><div className="hidden md:block"><Button onClick={() => openWhatsApp('nav')}>Falar no WhatsApp</Button></div><button className="rounded-full border border-border p-3 md:hidden" aria-label="Abrir menu" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X className="size-5" /> : <Menu className="size-5" />}</button></div>{menuOpen && <div className="border-t border-border bg-background px-5 py-5 md:hidden"><div className="flex flex-col gap-5 text-sm"><a href="#solucoes" onClick={() => setMenuOpen(false)}>Soluções</a><a href="#portfolio" onClick={() => setMenuOpen(false)}>Portfólio</a><a href="#processo" onClick={() => setMenuOpen(false)}>Como funciona</a><a href="#faq" onClick={() => setMenuOpen(false)}>FAQ</a><Button onClick={() => openWhatsApp('mobile-nav')}>Falar no WhatsApp</Button></div></div>}</nav>
    <section id="inicio" className="relative px-5 pb-20 pt-36 lg:px-8 lg:pb-28 lg:pt-48"><div className="mx-auto grid max-w-7xl items-center gap-16 lg:grid-cols-[1.05fr_.95fr]"><div><div className="mb-8 flex items-center gap-3 text-xs uppercase tracking-[0.22em] text-muted-foreground"><span className="size-2 rounded-full bg-foreground" /> Experiências digitais para negócios locais</div><h1 className="max-w-3xl text-balance font-serif text-6xl leading-[.92] tracking-[-0.05em] sm:text-7xl lg:text-[7rem]">Seu negócio ainda usa <span className="text-muted-foreground">cardápio em PDF?</span></h1><p className="mt-8 max-w-xl text-lg leading-8 text-muted-foreground">Transforme seu cardápio ou presença digital em uma experiência moderna, profissional e fácil de usar.</p><p className="mt-5 max-w-lg text-sm leading-6 text-muted-foreground/75">Na Vellora, criamos experiências digitais pensadas para apresentar seu negócio, facilitar a jornada do cliente e gerar mais oportunidades.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button onClick={() => openWhatsApp('hero')}>Quero modernizar meu negócio</Button><Button outline href={PORTFOLIO_URL} onClick={() => window.dispatchEvent(new CustomEvent('vellora_conversion', { detail: { event: 'portfolio_click', label: 'hero' } }))}>Ver projetos</Button></div><p className="mt-7 text-xs text-muted-foreground">Design profissional <span className="mx-2 text-border">•</span> Experiência mobile <span className="mx-2 text-border">•</span> Soluções sob medida</p></div><div className="hero-visual"><div className="browser-mockup"><div className="flex items-center gap-2 border-b border-border px-4 py-3"><span className="size-2 rounded-full bg-border" /><span className="size-2 rounded-full bg-border" /><span className="size-2 rounded-full bg-border" /><div className="ml-3 h-5 flex-1 rounded bg-muted" /></div><div className="bg-accent/30 p-7"><div className="flex items-center justify-between text-[9px] font-semibold"><span>CASA NOSTRA</span><span className="text-muted-foreground">MENU &nbsp; RESERVAS</span></div><div className="grid min-h-72 grid-cols-2 items-center gap-5 py-8"><div><div className="mb-4 h-2 w-1/2 bg-foreground/80" /><div className="h-8 w-4/5 bg-foreground/10" /><div className="mt-2 h-8 w-3/5 bg-foreground/10" /><div className="mt-5 h-7 w-24 rounded-full bg-foreground" /></div><div className="h-48 rounded-sm border border-border bg-muted" /></div></div></div><div className="phone-float"><PhoneMockup modern /></div><div className="absolute -bottom-6 left-4 hidden rounded-full border border-border bg-background px-4 py-3 text-[10px] shadow-xl sm:block">Experiência criada para converter</div></div></div></section>
    <section className="border-y border-border bg-accent/40 px-5 py-16 lg:px-8"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.9fr_1.1fr]"><SectionTitle title="Seu PDF não representa a qualidade do seu negócio." text="Um arquivo pode até carregar informações. Mas não deveria ser o ponto final da experiência do seu cliente." /><div className="grid grid-cols-2 gap-px self-start border border-border bg-border sm:grid-cols-3">{['Experiência ruim no celular','Necessidade de dar zoom','Navegação pouco intuitiva','Visual desatualizado','Difícil de atualizar','Não valoriza os produtos'].map((item, i) => <div key={item} className="bg-background p-5 sm:p-6"><span className="font-mono text-xs text-muted-foreground">0{i+1}</span><p className="mt-10 text-sm leading-5">{item}</p></div>)}</div></div></section>
    <section className="px-5 py-24 lg:px-8 lg:py-36"><div className="mx-auto max-w-7xl"><SectionTitle eyebrow="A EXPERIÊNCIA MOBILE" title="Seu cliente não deveria precisar dar zoom para escolher o que comprar." text="Uma experiência pensada para o celular torna a descoberta mais simples, rápida e agradável." /><div className="mt-16 grid items-center gap-10 md:grid-cols-2"><div className="flex flex-col items-center gap-6"><div className="flex items-end gap-4"><PhoneMockup /><div className="hidden pb-10 text-right text-xs text-muted-foreground sm:block">Cardápio em PDF<br /><span className="text-foreground">Leitura difícil.</span></div></div><span className="border border-border px-4 py-2 text-xs">Cardápio em PDF</span></div><div className="flex flex-col items-center gap-6"><div className="flex items-end gap-4"><div className="hidden pb-10 text-left text-xs text-muted-foreground sm:block">Experiência Vellora<br /><span className="text-foreground">Tudo no lugar.</span></div><PhoneMockup modern /></div><span className="bg-foreground px-4 py-2 text-xs text-background">Experiência Vellora</span></div></div><div className="mt-12 flex flex-wrap justify-center gap-2 text-xs text-muted-foreground">{['Navegação fácil','Botões grandes','Imagens de produtos','Categorias claras','Acesso rápido','CTA para WhatsApp','Mobile-first'].map(x => <span key={x} className="rounded-full border border-border px-4 py-2">{x}</span>)}</div></div></section>
    <section className="bg-foreground px-5 py-24 text-background lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><SectionTitle light eyebrow="A TRANSFORMAÇÃO" title="Do PDF para uma experiência digital." text="Seu negócio merece uma presença digital à altura da qualidade que você oferece." /><div className="mt-16 grid gap-px border border-background/15 bg-background/15 md:grid-cols-2"><div className="bg-background/5 p-7 sm:p-10"><div className="flex items-center justify-between border-b border-background/15 pb-6"><span className="font-serif text-2xl">Cardápio em PDF</span><span className="text-xs text-background/40">ANTES</span></div><ul className="mt-8 flex flex-col gap-5 text-sm text-background/55">{['Zoom constante','Navegação limitada','Visual simples','Difícil atualização'].map(x => <li key={x} className="flex gap-3"><X className="size-4" />{x}</li>)}</ul></div><div className="bg-background p-7 text-foreground sm:p-10"><div className="flex items-center justify-between border-b border-border pb-6"><span className="font-serif text-2xl">Experiência Vellora</span><span className="text-xs text-muted-foreground">DEPOIS</span></div><ul className="mt-8 flex flex-col gap-5 text-sm">{['Responsivo','Navegação intuitiva','Visual premium','Fácil atualização','Otimizado para celular','Mais praticidade'].map(x => <li key={x} className="flex gap-3"><Check className="size-4" />{x}</li>)}</ul></div></div></div></section>
    <section id="solucoes" className="px-5 py-24 lg:px-8 lg:py-36"><div className="mx-auto max-w-7xl"><SectionTitle title="O que a Vellora pode criar para você" text="Soluções digitais com intenção, estética e clareza para o momento do seu negócio." /><div className="mt-14 grid gap-px border border-border bg-border sm:grid-cols-2 lg:grid-cols-3">{services.map(([title, text], i) => <article key={title} className="group bg-background p-7 transition-colors hover:bg-accent sm:p-9"><div className="flex items-center justify-between"><Sparkles className="size-5 text-muted-foreground" /><span className="font-mono text-xs text-muted-foreground">0{i+1}</span></div><h3 className="mt-16 font-serif text-2xl">{title}</h3><p className="mt-4 text-sm leading-6 text-muted-foreground">{text}</p><MoveRight className="mt-8 size-5 transition-transform group-hover:translate-x-2" /></article>)}</div></div></section>
    <section className="border-y border-border bg-accent/40 px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><SectionTitle title="Não entregamos apenas um site." text="Criamos experiências digitais pensadas para o seu negócio e para as pessoas que compram de você." /><div className="grid gap-px border border-border bg-border sm:grid-cols-2">{[['Pensado para o seu negócio','Cada projeto é desenvolvido considerando a identidade, público e objetivo da empresa.'],['Experiência mobile','Seu cliente acessa pelo celular? Então o projeto é pensado primeiro para ele.'],['Design que valoriza sua marca','Uma apresentação profissional aumenta a percepção de valor do seu negócio.'],['Foco em conversão','Cada elemento da página tem uma função: informar, gerar confiança ou incentivar uma ação.']].map(([title,text]) => <div key={title} className="bg-background p-7"><h3 className="font-serif text-xl">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></div>)}</div></div></div></section>
    <section className="px-5 py-24 lg:px-8 lg:py-36"><div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-2"><div><span className="eyebrow">POR QUE MODERNIZAR?</span><h2 className="mt-5 max-w-xl text-balance font-serif text-5xl leading-[1.05] tracking-tight">Uma presença digital que trabalha pelo seu negócio.</h2><p className="mt-6 max-w-lg leading-7 text-muted-foreground">Cada detalhe pode facilitar a escolha, apresentar melhor o que você oferece e abrir uma nova conversa com seus clientes.</p></div><div className="grid gap-px border border-border bg-border sm:grid-cols-2">{benefits.map(([title,text]) => <div key={title} className="bg-background p-6"><Check className="size-4" /><h3 className="mt-8 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div>)}</div></div></section>
    <section className="bg-foreground px-5 py-24 text-background lg:px-8 lg:py-32"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-2"><div><SectionTitle light title="Pare de perder oportunidades por causa de uma presença digital desatualizada." text="Seu negócio já investe em produtos, atendimento e estrutura. Sua presença digital também precisa estar à altura." /><div className="mt-8"><Button onClick={() => openWhatsApp('offer')}>Quero modernizar meu negócio</Button></div></div><div className="flex items-center justify-center gap-3 opacity-90"><div className="h-56 w-40 rotate-[-7deg] border border-background/20 bg-background/5 p-4"><div className="flex flex-col gap-2 opacity-40">{[1,2,3,4,5,6,7].map(i => <div key={i} className="h-2 bg-background/60" />)}</div></div><MoveRight className="size-6 text-background/50" /><div className="h-64 w-44 rotate-[5deg] border border-background/40 bg-background p-4 text-foreground shadow-2xl"><div className="h-20 bg-muted" /><div className="mt-4 h-3 w-3/4 bg-foreground" /><div className="mt-2 h-2 w-1/2 bg-muted-foreground/30" /><div className="mt-8 h-8 rounded-full bg-foreground" /></div></div></div></section>
    <section className="px-5 py-24 lg:px-8 lg:py-36"><div className="mx-auto grid max-w-7xl items-start gap-16 lg:grid-cols-2"><SectionTitle eyebrow="PRESENÇA DIGITAL LOCAL" title="Seu negócio pronto para ser encontrado." text="Uma presença digital bem estruturada ajuda seu negócio a apresentar informações importantes para clientes que estão procurando por você." /><div><ul className="grid grid-cols-2 gap-x-8 gap-y-5 border-y border-border py-8 text-sm">{['Site profissional','Domínio próprio','Informações do negócio','Localização','Horários','WhatsApp','Links importantes','Estrutura preparada para SEO'].map(x => <li key={x} className="flex items-center gap-3"><Check className="size-4 text-muted-foreground" />{x}</li>)}</ul><div className="mt-8"><Button onClick={() => openWhatsApp('local-business')}>Quero melhorar minha presença digital</Button></div></div></div></section>
    <section id="portfolio" className="border-y border-border bg-accent/40 px-5 py-24 lg:px-8 lg:py-36"><div className="mx-auto max-w-7xl"><SectionTitle title="Alguns projetos da Vellora" text="Conheça alguns dos projetos que desenvolvemos para transformar negócios em experiências digitais." /><div className="mt-14 grid gap-4 md:grid-cols-3">{[1,2,3].map(i => <div key={i} className="portfolio-slot"><div className="portfolio-placeholder"><span className="font-mono text-xs tracking-[.2em]">PROJETO EM BREVE</span><div className="mt-5 h-px w-16 bg-border" /></div><div className="flex items-end justify-between gap-3 pt-5"><div><div className="h-4 w-32 bg-muted" /><div className="mt-2 h-3 w-24 bg-muted" /></div><span className="rounded-full border border-border px-3 py-2 text-xs">Ver projeto</span></div></div>)}</div><div className="mt-12 text-center"><Button outline onClick={() => openWhatsApp('portfolio-bottom')}>Quero um projeto assim</Button></div></div></section>
    <section id="processo" className="px-5 py-24 lg:px-8 lg:py-36"><div className="mx-auto max-w-7xl"><SectionTitle title="Simples, rápido e profissional." text="Do primeiro contato à publicação, cada etapa é conduzida com clareza." /><div className="mt-14 grid border-y border-border md:grid-cols-4">{[['01','Você entra em contato','Conte para a gente sobre o seu negócio e o que você precisa.'],['02','Entendemos seu negócio','Analisamos suas necessidades e definimos a melhor solução.'],['03','Desenvolvemos seu projeto','Criamos uma experiência visual moderna, responsiva e alinhada à sua marca.'],['04','Você recebe sua nova experiência digital','Seu negócio ganha uma presença digital profissional pronta para seus clientes.']].map(([num,title,text]) => <div key={num} className="border-b border-border py-8 md:border-b-0 md:border-r md:p-7 md:last:border-r-0"><span className="font-mono text-xs text-muted-foreground">{num}</span><h3 className="mt-10 font-serif text-xl">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></div>)}</div><div className="mt-10"><Button onClick={() => openWhatsApp('process')}>Falar com a Vellora</Button></div></div></section>
    <section className="bg-accent/40 px-5 py-24 lg:px-8"><div className="mx-auto max-w-7xl"><SectionTitle title="Feito para negócios que querem evoluir." text="Se o seu negócio depende de clientes, uma boa presença digital importa." /><div className="mt-12 flex flex-wrap gap-3">{['Restaurantes','Lanchonetes','Pizzarias','Bares','Cafeterias','Hotéis','Pousadas','Salões de beleza','Clínicas','Lojas','Prestadores de serviços','Pequenos negócios locais'].map(x => <span key={x} className="rounded-full border border-border bg-background px-5 py-3 text-sm">{x}</span>)}</div></div></section>
    <section id="briefing" className="px-5 py-24 lg:px-8 lg:py-36"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.8fr_1.2fr]"><div><SectionTitle title="Conte um pouco sobre o seu negócio." text="Quanto mais entendermos, melhor poderemos pensar na experiência certa para você." /></div><div>{submitted ? <div className="border border-border bg-accent/40 p-10"><Check className="size-8" /><h3 className="mt-8 font-serif text-3xl">Recebemos suas informações.</h3><p className="mt-4 text-muted-foreground">Obrigado pelo contato. Em breve, a Vellora falará com você para entender o próximo passo.</p></div> : <form className="grid gap-5" onSubmit={(e) => { e.preventDefault(); setSubmitted(true); window.dispatchEvent(new CustomEvent('vellora_conversion', { detail: { event: 'quote_form_submit' } })) }}><div className="grid gap-5 sm:grid-cols-2"><input required placeholder="Nome" className="form-input" /><input required placeholder="Nome do negócio" className="form-input" /></div><div className="grid gap-5 sm:grid-cols-2"><input placeholder="Segmento" className="form-input" /><input required placeholder="WhatsApp" className="form-input" /></div><div className="grid gap-5 sm:grid-cols-2"><input placeholder="Instagram" className="form-input" /><select className="form-input" defaultValue=""><option value="" disabled>O que você precisa?</option><option>Landing Page</option><option>Site profissional</option><option>Cardápio digital</option><option>Site para restaurante</option><option>Página para campanha</option><option>Ainda não sei</option></select></div><input placeholder="Link do site ou cardápio atual" className="form-input" /><select className="form-input" defaultValue=""><option value="" disabled>Já possui domínio?</option><option>Sim</option><option>Não</option><option>Não sei</option></select><button className="mt-3 inline-flex min-h-12 items-center justify-center gap-3 rounded-full bg-foreground px-6 text-sm font-semibold text-background" type="submit">Solicitar orçamento <ArrowUpRight className="size-4" /></button><p className="text-xs text-muted-foreground">Suas informações serão usadas apenas para entrarmos em contato.</p></form>}</div></div></section>
    <section id="faq" className="border-t border-border px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.75fr_1.25fr]"><SectionTitle title="Perguntas frequentes" text="Tudo o que você precisa saber para começar a transformar sua presença digital." /><div className="border-t border-border">{faqs.map(([q,a], i) => <div key={q} className="border-b border-border"><button className="flex w-full items-center justify-between gap-4 py-6 text-left text-sm font-medium" onClick={() => setFaqOpen(faqOpen === i ? null : i)} aria-expanded={faqOpen === i}>{q}<ChevronDown className={`size-4 transition-transform ${faqOpen === i ? 'rotate-180' : ''}`} /></button>{faqOpen === i && <p className="max-w-2xl pb-6 pr-8 text-sm leading-6 text-muted-foreground">{a}</p>}</div>)}</div></div></section>
    <section className="bg-foreground px-5 py-28 text-background lg:px-8 lg:py-40"><div className="mx-auto flex max-w-4xl flex-col items-center text-center"><Logo /><h2 className="mt-12 text-balance font-serif text-5xl leading-[1] tracking-tight sm:text-7xl">Seu negócio está pronto para sair do PDF?</h2><p className="mt-7 max-w-xl text-base leading-7 text-background/60">Vamos transformar sua presença digital em algo que seus clientes realmente tenham vontade de usar.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button onClick={() => openWhatsApp('final')}>Falar com a Vellora no WhatsApp</Button><Button outline onClick={() => document.getElementById('briefing')?.scrollIntoView({ behavior: 'smooth' })}>Solicitar orçamento</Button></div></div></section>
    <footer className="bg-foreground px-5 pb-24 pt-8 text-background/50 lg:px-8 lg:pb-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-4 border-t border-background/15 pt-6 text-xs sm:flex-row"><span>© 2026 Vellora. Experiências digitais profissionais.</span><span>Feito para negócios que querem evoluir.</span></div></footer>
    <button className="whatsapp-float" onClick={() => openWhatsApp('floating')} aria-label="Falar no WhatsApp"><MessageCircle className="size-5" /><span>Falar no WhatsApp</span></button><div className="mobile-cta"><button onClick={() => openWhatsApp('mobile-sticky')}>Quero modernizar meu negócio <ArrowUpRight className="size-4" /></button></div>
  </main>
}
